# Generated by Django 5.0 on 2023-12-21 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=100, null=True)),
                ('category', models.CharField(max_length=300, null=True)),
                ('breed', models.CharField(max_length=200, null=True)),
                ('desc', models.CharField(max_length=500, null=True)),
                ('price', models.FloatField(null=True)),
            ],
        ),
    ]
