# Generated by Django 5.0 on 2023-12-21 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animals',
            name='image',
            field=models.ImageField(null=True, upload_to='media'),
        ),
    ]
