# Generated by Django 5.0 on 2023-12-23 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petApp', '0002_animals_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.IntegerField(null=True)),
                ('animals', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='petApp.animals')),
            ],
        ),
    ]
