# Generated by Django 5.0 on 2023-12-30 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petApp', '0004_remove_cart_cid'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name12', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
