# Generated by Django 5.0 on 2023-12-30 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petApp', '0005_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
