# Generated by Django 5.0 on 2023-12-31 13:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petApp', '0008_cart_user_delete_user1'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100, null=True)),
                ('pincode', models.IntegerField(null=True)),
                ('detail', models.CharField(max_length=500, null=True)),
                ('state', models.CharField(max_length=100, null=True)),
                ('animals', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petApp.animals')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
