# Generated by Django 5.0 on 2024-01-06 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petApp', '0012_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='alternate_phone',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='phone',
            field=models.BigIntegerField(null=True),
        ),
    ]
