# Generated by Django 5.0 on 2024-01-15 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petApp', '0016_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='amount',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='petApp.order'),
        ),
    ]
