# Generated by Django 5.0 on 2024-01-15 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petApp', '0017_amount_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Amount',
        ),
    ]
