# Generated by Django 5.0.2 on 2024-02-21 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petApp', '0019_order_delivery_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order_History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField()),
                ('pname', models.CharField(max_length=100, null=True)),
                ('category', models.CharField(max_length=300, null=True)),
                ('breed', models.CharField(max_length=200, null=True)),
                ('desc', models.CharField(max_length=500, null=True)),
                ('price', models.FloatField(null=True)),
                ('image', models.ImageField(null=True, upload_to='media')),
            ],
        ),
    ]
