# Generated by Django 5.0.2 on 2024-03-07 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petApp', '0020_order_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_history',
            name='alternate_phone',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='order_history',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order_history',
            name='cname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order_history',
            name='detail',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='order_history',
            name='phone',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='order_history',
            name='pincode',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='order_history',
            name='state',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order_history',
            name='user',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
